[package]
name = "everybody_codes"
version = "0.1.0"
edition = "2024"

[dependencies]
cgmath = "0.18.0"
copypasta = "0.10.2"
num = "0.4.3"
rand = "0.9.2"
rayon = "1.11.0"
regex = "1.12.2"
sscanf = "0.4.4"
